<?php
/**
 * Author: Yusuf Shakeel
 * Date: 14-jun-2019 fri
 * Version: 1.0
 *
 * File: Constants.php
 * Description: This file contains constants.
 */

namespace GetStorifyOffers\Config;

define('GETSTORIFY_OFFERS_WEBSITE_APP_VERSION', '1.0.0');

define('SESSION_GETSTORIFY_OFFERS_API_SERVICE_AUTH_ACCESSTOKEN', 'SESSION_GETSTORIFY_OFFERS_API_SERVICE_AUTH_ACCESSTOKEN');

define('GETSTORIFY_OFFERS_API_SERVICE_BASE_URL', 'https://api.getstorify.com');
define('GETSTORIFY_OFFERS_BASE_URL', 'https://getstorify.com/storify');

define('GETSTORIFY_OFFERS_API_SERVICE_USER_AUTH_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/auth');
define('GETSTORIFY_OFFERS_API_SERVICE_USER_AUTH_ACCESS_TOKEN_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/auth/accesstoken');

/**
 * Put your Google API Key here.
 */
define('GETSTORIFY_OFFERS_API_SERVICE_GOOGLE_API_KEY_WEB_KEY', '');

// User APIs
define('GETSTORIFY_OFFERS_API_SERVICE_USER_DETAIL_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/user');
define('GETSTORIFY_OFFERS_API_SERVICE_STORES_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/stores');
define('GETSTORIFY_OFFERS_API_SERVICE_STORES_WITH_LIVE_OFFERS_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/stores/withliveoffers');
define('GETSTORIFY_OFFERS_API_SERVICE_OFFERS_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/offers');
define('GETSTORIFY_OFFERS_API_SERVICE_OFFERS_LIVE_POPULAR_OFFERS_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/offers/livepopularoffers');
define('GETSTORIFY_OFFERS_API_SERVICE_OFFERS_ITEMS_URL', GETSTORIFY_OFFERS_API_SERVICE_BASE_URL . '/v1/user/offeritems');

define('GETSTORIFY_OFFERS_API_SERVICE_DB_PAGE_LIMIT', 10);